package hw8;

/**
 * Class provided for ease of test. This will not be used in the project
 * evaluation, so feel free to modify it as you like.
 */
public class Simulation {
	public static void main(String[] args) {
		int nrSellers = 50;
		int nrBidders = 20;

		Thread[] sellerThreads = new Thread[nrSellers];
		Thread[] bidderThreads = new Thread[nrBidders];
		Seller[] sellers = new Seller[nrSellers];
		Bidder[] bidders = new Bidder[nrBidders];

		// Start the sellers
		for (int i = 0; i < nrSellers; ++i) {
			sellers[i] = new Seller(AuctionServer.getInstance(), "Seller" + i, 100, 50, i);
			sellerThreads[i] = new Thread(sellers[i]);
			sellerThreads[i].start();
		}

		// Start the buyers
		for (int i = 0; i < nrBidders; ++i) {
			bidders[i] = new Bidder(AuctionServer.getInstance(), "Buyer" + i, 1000, 20, 150, i);
			bidderThreads[i] = new Thread(bidders[i]);
			bidderThreads[i].start();
		}

		// Join on the sellers
		for (int i = 0; i < nrSellers; ++i) {
			try {
				sellerThreads[i].join();
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}

		// Join on the bidders
		for (int i = 0; i < nrBidders; ++i) {
			try {
				sellerThreads[i].join();
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}

		// TODO: Add code as needed to debug
		AuctionServer.getInstance().getTimer().cancel();
		int cashSpent = 0;
		for (Bidder bidder : bidders) {
			cashSpent = cashSpent + bidder.cashSpent();
		}
		int revenue = AuctionServer.getInstance().revenue();
		if (revenue == cashSpent) {
			System.out.println("Total Cash spent by Bidders " + cashSpent);
			System.out.println("Revenue generated by the server " + revenue);
			System.out.println("Total cash spent is equal to the revenue generated.");
		}
		int soldItem = AuctionServer.getInstance().getSoldItemCount();
		int unsoldItems = AuctionServer.getInstance().getUnSoldItemCount();
		System.out.println("Total items sold " + soldItem);
		System.out.println("Total items unsold " + unsoldItems);
		System.out.println("Total items listed  " + AuctionServer.getInstance().totalItemsListed());
		if (AuctionServer.getInstance().totalItemsListed() == soldItem + unsoldItems) {
			System.out.println("Total items listed equals sold + unsold.");
			System.out.println("Auction Successful !!!");
		}

	}
}